In [38]:
# Load the modules and be done with them
import theano as th
from keras.models import Sequential
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from  keras.layers.convolutional import Conv1D
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [4]:
glen_H_data_raw = pd.read_csv("../Labeled_glen_2017-03-19_to_2017-03-23_simplified.csv", index_col=0)

In [5]:
np.random.seed(102849201)

In [6]:
glen_H_data = glen_H_data_raw[['Acceleration x','Acceleration y','Acceleration z',
                               'Magnetometer x','Magnetometer y','Magnetometer z',\
                               'classification']]
#glen_H_data = glen_H_data.dropna()#glen_H_data = glen_H_data.dropna()
glen_H_data.iloc[:,0:6].astype(float)
glen_H_data['Acceleration'] =  np.sqrt(glen_H_data['Acceleration x']**2 + glen_H_data['Acceleration y']**2 +\
                                       glen_H_data['Acceleration z']**2)
glen_H_data['Magnetometer'] =  np.sqrt(glen_H_data['Magnetometer x']**2 + glen_H_data['Magnetometer y']**2 +\
                                       glen_H_data['Magnetometer z']**2)
#glen_H_data['Gyrometer']    =  np.sqrt(glen_H_data['Gyrometer x']**2 + glen_H_data['Gyrometer y']**2 +\
#                                       glen_H_data['Gyrometer z']**2)
#glen_H_data['Microphone']    =  (glen_H_data['Microphone Left Channel Level'] +\
#                                glen_H_data['Microphone Right Channel Level'])/2
#glen_H_data = glen_H_data[['Acceleration','Magnetometer','Gyrometer','Microphone','Altimeter (Barometer) Pressure', 'classification']]
glen_H_data = glen_H_data[['Acceleration', 'Magnetometer', 'classification']]
# set window 1
window = 2
# Rolling Means
glen_H_data['RollingMeanAcceleration2'] = glen_H_data['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data['RollingMeanMagnetometer2'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data['RollingSDAcceleration2'] = glen_H_data['Acceleration'].rolling(window=window,center=False).std()
glen_H_data['RollingSDMagnetometer2'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data['RollingMeanAcceleration2'] = glen_H_data['Acceleration'].rolling(window=window,center=False).max()
glen_H_data['RollingMaxMagnetometer2'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).max()

# set window 2
window = 5
# Rolling Means
glen_H_data['RollingMeanAcceleration5'] = glen_H_data['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data['RollingMeanMagnetometer5'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data['RollingSDAcceleration5'] = glen_H_data['Acceleration'].rolling(window=window,center=False).std()
glen_H_data['RollingSDMagnetometer5'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data['RollingMeanAcceleration5'] = glen_H_data['Acceleration'].rolling(window=window,center=False).max()
glen_H_data['RollingMaxMagnetometer5'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).max()

# set window 3
window = 7
# Rolling Means
glen_H_data['RollingMeanAcceleration7'] = glen_H_data['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data['RollingMeanMagnetometer7'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data['RollingSDAcceleration7'] = glen_H_data['Acceleration'].rolling(window=window,center=False).std()
glen_H_data['RollingSDMagnetometer7'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data['RollingMeanAcceleration7'] = glen_H_data['Acceleration'].rolling(window=window,center=False).max()
glen_H_data['RollingMaxMagnetometer7'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).max()

# set window 4
window = 10
# Rolling Means
glen_H_data['RollingMeanAcceleration10'] = glen_H_data['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data['RollingMeanMagnetometer10'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data['RollingSDAcceleration10'] = glen_H_data['Acceleration'].rolling(window=window,center=False).std()
glen_H_data['RollingSDMagnetometer10'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data['RollingMeanAcceleration10'] = glen_H_data['Acceleration'].rolling(window=window,center=False).max()
glen_H_data['RollingMaxMagnetometer10'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).max()

# set window 5
window = 15
# Rolling Means
glen_H_data['RollingMeanAcceleration15'] = glen_H_data['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data['RollingMeanMagnetometer15'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data['RollingSDAcceleration15'] = glen_H_data['Acceleration'].rolling(window=window,center=False).std()
glen_H_data['RollingSDMagnetometer15'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data['RollingMeanAcceleration15'] = glen_H_data['Acceleration'].rolling(window=window,center=False).max()
glen_H_data['RollingMaxMagnetometer15'] = glen_H_data['Magnetometer'].rolling(window=window,center=False).max()
glen_H_data = glen_H_data.dropna()
glen_H_data_re = glen_H_data.iloc[:,range(0,2) + range(3,28) + [2]]

/Users/gafergus/anaconda/envs/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/gafergus/anaconda/envs/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [18]:
# load dataset
dataset = glen_H_data_re.values
X = dataset[:,0:26]
X = preprocessing.scale(X)
Y = dataset[:,27]
#convert integers to dummy variables (i.e. one hot encoded)
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

In [23]:
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(300, input_dim=26, init='normal', activation='sigmoid'))
    model.add(Dense(100, init='normal', activation='sigmoid'))
    model.add(Dense(50, init='normal', activation='sigmoid'))
    model.add(Dense(6, init='normal', activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [24]:
estimator = KerasClassifier(build_fn=baseline_model, nb_epoch=200, batch_size=5, verbose=0)

In [25]:
kfold = KFold(n_splits=5, shuffle=True, random_state=73472991)

In [26]:
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Baseline: 87.37% (1.02%)


In [28]:
estimator.fit(X, dummy_y)

In [30]:
glen_H_data_TEST_raw = pd.read_csv('../glen_3_24_labeled.csv', index_col=0)
#Use this cell if you want to simplify your labels
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='T_E', value='T_S')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='E_U', value='E')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='E_D', value='E')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='S_U', value='W')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='S_D', value='W')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='T_T', value='T_S')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='T_B', value='T_D')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='P_W', value='W')
glen_H_data_TEST_raw = glen_H_data_TEST_raw.replace(to_replace='P_S', value='S')
glen_H_data_TEST_raw.groupby("classification").size()

classification
D      150
E        8
S       37
T_D    297
T_S     84
W      255
dtype: int64

In [31]:
glen_H_data_TEST = glen_H_data_TEST_raw[['Acceleration x','Acceleration y','Acceleration z',
                                         'Magnetometer x','Magnetometer y','Magnetometer z',\
                                         'classification']]
glen_H_data_TEST.iloc[:,0:6].astype(float)

Acceleration x  Acceleration y  Acceleration z  \
2017-03-24 06:31:10        0.000000        0.000000        0.000000   
2017-03-24 06:31:15       -0.023296       -0.018811        0.066937   
2017-03-24 06:31:19       -0.015955        0.008646        0.017675   
2017-03-24 06:31:24       -0.027630       -0.027705       -0.014916   
2017-03-24 06:31:28        0.080779       -0.055970       -0.106723   
2017-03-24 06:31:33        0.242347        0.272881       -0.190725   
2017-03-24 06:31:37       -0.007537        0.121181       -0.137641   
2017-03-24 06:31:42       -0.460572       -0.016713        0.077979   
2017-03-24 06:31:46       -0.029696       -0.123480       -0.279018   
2017-03-24 06:31:51       -0.035942        0.019347       -0.053827   
2017-03-24 06:31:55        0.047630       -0.051640        0.075338   
2017-03-24 06:32:00       -0.192916        0.095040       -0.115912   
2017-03-24 06:32:04       -0.022090       -0.010550        0.119714   
2017-03-24 06:32:09       -0.110702        0.072385        0.027058   
2017-03-24 06:32:13        0.148126        0.185532        0.192337   
2017-03-24 06:32:18        0.244598       -0.095402        0.108336   
2017-03-24 06:32:22       -0.101266       -0.030007       -0.036007   
2017-03-24 06:32:27        0.146127       -0.148097       -0.009419   
2017-03-24 06:32:31        0.075659       -0.022485       -0.120662   
2017-03-24 06:32:36        0.075854        0.324866       -0.143607   
2017-03-24 06:32:40        0.019261        0.082247       -0.054385   
2017-03-24 06:32:45       -0.005573       -0.046098        0.034757   
2017-03-24 06:32:49        0.003922       -0.019715       -0.089746   
2017-03-24 06:32:54       -0.006603       -0.017521       -0.066441   
2017-03-24 06:32:58       -0.001972       -0.002442        0.006742   
2017-03-24 06:33:03        0.004168        0.007355       -0.015515   
2017-03-24 06:33:07        0.010826       -0.001434       -0.021446   
2017-03-24 06:33:12       -0.001449       -0.001893       -0.008430   
2017-03-24 06:33:16        0.000397       -0.001864       -0.013703   
2017-03-24 06:33:21        0.010886        0.002509       -0.012407   
...                             ...             ...             ...   
2017-03-24 07:31:18        0.206629       -0.276488       -0.199973   
2017-03-24 07:31:22        0.197690       -0.214692       -0.055040   
2017-03-24 07:31:27        0.034104       -0.068547       -0.058620   
2017-03-24 07:31:31        0.087880        0.284720       -0.281782   
2017-03-24 07:31:36       -0.663411        1.016563       -0.095528   
2017-03-24 07:31:40        0.472822       -0.033457       -0.477229   
2017-03-24 07:31:45        0.282069       -0.123534       -0.276272   
2017-03-24 07:31:49        0.082615        0.218475        0.066093   
2017-03-24 07:31:54       -0.168447       -0.069317       -0.000332   
2017-03-24 07:31:58        0.451907       -0.234358        0.054017   
2017-03-24 07:32:03       -0.028112       -0.005054        0.221233   
2017-03-24 07:32:07        0.243476       -0.121590        0.119209   
2017-03-24 07:32:12       -0.093777       -0.003072        0.240656   
2017-03-24 07:32:16       -0.028875        0.023101        0.013803   
2017-03-24 07:32:21        0.042602       -0.024998        0.027209   
2017-03-24 07:32:25        0.289845        0.455049        0.175118   
2017-03-24 07:32:30       -0.089987        0.247746        0.424287   
2017-03-24 07:32:34       -0.022498        0.019356       -0.036111   
2017-03-24 07:32:39        0.030337       -0.040820        0.150992   
2017-03-24 07:32:43        0.004287       -0.093526       -0.052685   
2017-03-24 07:32:48       -0.028473       -0.014445        0.016382   
2017-03-24 07:32:52       -0.185083        0.280843       -0.276816   
2017-03-24 07:32:57        0.049816        0.006153       -0.029789   
2017-03-24 07:33:01       -0.074898       -0.005934       -0.003584   
2017-03-24 07:33:06        0.261323       -0.

In [32]:
glen_H_data_TEST['Acceleration'] =  np.sqrt(glen_H_data_TEST['Acceleration x']**2 + glen_H_data_TEST['Acceleration y']**2 +\
                                            glen_H_data_TEST['Acceleration z']**2)
glen_H_data_TEST['Magnetometer'] =  np.sqrt(glen_H_data_TEST['Magnetometer x']**2 + glen_H_data_TEST['Magnetometer y']**2 +\
                                            glen_H_data_TEST['Magnetometer z']**2)
glen_H_data_TEST = glen_H_data_TEST[['Acceleration','Magnetometer','classification']]
# set window 1
window = 2
# Rolling Means
glen_H_data_TEST['RollingMeanAcceleration2'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data_TEST['RollingMeanMagnetometer2'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data_TEST['RollingSDAcceleration2'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).std()
glen_H_data_TEST['RollingSDMagnetometer2'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data_TEST['RollingMeanAcceleration2'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).max()
glen_H_data_TEST['RollingMaxMagnetometer2'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).max()

# set window 2
window = 5
# Rolling Means
glen_H_data_TEST['RollingMeanAcceleration5'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data_TEST['RollingMeanMagnetometer5'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data_TEST['RollingSDAcceleration5'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).std()
glen_H_data_TEST['RollingSDMagnetometer5'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data_TEST['RollingMeanAcceleration5'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).max()
glen_H_data_TEST['RollingMaxMagnetometer5'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).max()

# set window 3
window = 7
# Rolling Means
glen_H_data_TEST['RollingMeanAcceleration7'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data_TEST['RollingMeanMagnetometer7'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data_TEST['RollingSDAcceleration7'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).std()
glen_H_data_TEST['RollingSDMagnetometer7'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data_TEST['RollingMeanAcceleration7'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).max()
glen_H_data_TEST['RollingMaxMagnetometer7'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).max()

# set window 4
window = 10
# Rolling Means
glen_H_data_TEST['RollingMeanAcceleration10'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data_TEST['RollingMeanMagnetometer10'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data_TEST['RollingSDAcceleration10'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).std()
glen_H_data_TEST['RollingSDMagnetometer10'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data_TEST['RollingMeanAcceleration10'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).max()
glen_H_data_TEST['RollingMaxMagnetometer10'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).max()

# set window 5
window = 15
# Rolling Means
glen_H_data_TEST['RollingMeanAcceleration15'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).mean()
glen_H_data_TEST['RollingMeanMagnetometer15'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).mean()
# Rolling st dev
glen_H_data_TEST['RollingSDAcceleration15'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).std()
glen_H_data_TEST['RollingSDMagnetometer15'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).std()
# Rolling Max
glen_H_data_TEST['RollingMeanAcceleration15'] = glen_H_data_TEST['Acceleration'].rolling(window=window,center=False).max()
glen_H_data_TEST['RollingMaxMagnetometer15'] = glen_H_data_TEST['Magnetometer'].rolling(window=window,center=False).max()
glen_H_data_TEST1 = glen_H_data_TEST.dropna()
glen_H_data_re_TEST = glen_H_data_TEST1.iloc[:,range(0,2) + range(3,28) + [2]]

/Users/gafergus/anaconda/envs/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/gafergus/anaconda/envs/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [34]:
# load dataset
dataset = glen_H_data_re_TEST.values
X = dataset[:,0:26]
X = preprocessing.scale(X)
Y = dataset[:,27]
#convert integers to dummy variables (i.e. one hot encoded)
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

In [39]:
Y_pred = estimator.predict(X)
print accuracy_score(encoded_Y,Y_pred)
print confusion_matrix(encoded_Y,Y_pred)

0.421052631579
[[ 57   0   3  12  64  14]
 [  0   1   0   0   0   7]
 [ 19   0   1   3   0  14]
 [ 33   0  10 115   5 134]
 [  3   0   0   4   9  68]
 [ 25   4   3  34  14 161]]
